apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "open-assistant-safe.fullname" . }}
  labels:
    app: {{ include "open-assistant-safe.name" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "open-assistant-safe.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "open-assistant-safe.name" . }}
    spec:
      containers:
        - name: api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8000
          env:
            - name: SERVER_HOST
              value: {{ .Values.env.SERVER_HOST | quote }}
            - name: SERVER_PORT
              value: {{ .Values.env.SERVER_PORT | quote }}
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 2
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10