version: "3.9"
services:
  assistant:
    build: .
    ports:
      - "8000:8000"
    environment:
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=8000
    volumes:
      - ./.env:/app/.env:ro
      - ./assistant_memory.sqlite3:/app/assistant_memory.sqlite3